### ISSUE TITLE
pkictl create-cert fails on invalid ca cert

### ISSUE THREAD

**Issue by FloRinke** [Gibheer/pkictl#13]
When trying to set up a simple ca and server+client cert, create-cert fails with stacktrace. Apparently this is caused by a Layer 8 Parser issue (public key != certificate), still an error message would be a more appropriate response.

To reproduce, run:
```
pkictl create-private -length 4096 -type rsa -output ca.key
pkictl create-private -length 4096 -type rsa -output server.key
pkictl create-public -private-key ca.key -output ca.crt
pkictl create-sign-request -common-name test-server -private-key server.key -serial 12345 -output server.csr 
pkictl create-cert -ca ca.crt -not-after "2018-07-31T23:59:59+02:00" -output server.crt -private-key server.key -serial 12345 -sign-request server.csr -usage server
```
This results in the following error and stacktrace:
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.getSectionFromPem(0xc420064870, 0x574231, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/fr/go-repo/src/github.com/Gibheer/pkictl/pem.go:29 +0x23c
main.parseCA(0x7ffc42a8b7fb, 0x6, 0x0, 0x0, 0x0)
        /home/fr/go-repo/src/github.com/Gibheer/pkictl/create_cert.go:186 +0x114
main.CreateCert(0xc420010120, 0xe, 0xe, 0x0, 0x0)
        /home/fr/go-repo/src/github.com/Gibheer/pkictl/create_cert.go:108 +0xebc
main.main()
        /home/fr/go-repo/src/github.com/Gibheer/pkictl/main.go:34 +0x1b2
```

**Comment by Gibheer** [comment]
A fix was committed yesterday and with c07b174 it should also return a proper message pointing to the file in question. More such messages are missing, but this should do it for now.
